version: "3.9"

services:
  app:
    build: .
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - lsg_shared
    environment:
      - DB_HOST=lsg_db
      - DB_PORT=3306
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    ports:
      - "8001:8000"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --proxy-headers --root-path /lsg-auth
    volumes:
      - .:/app

networks:
  lsg_shared:
    external: true
